name: Github Actions
on:
    pull_request:
      branches:
        - develop
        - main
    push:
      branches:
        - develop
        - main

defaults:
  run:
    working-directory: example

jobs:
  build_android:
    name: Build Android
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build appbundle

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      
  # build_web:
  #   name: Build Web
  #   runs-on: macos-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: "beta"
  #     - run: flutter pub get
  #     - run: flutter build web
  #     - run: flutter build web --web-renderer html